### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by leolara** [syyongx/php2go#1]

**Comment by rkl-** [comment]
As aked me `why` too :D. However, if you would implement `strtotime` full like in `PHP` with relative time formats, this would be really nice!

**Comment by syyongx** [comment]
For phper, they are used to the convenience of php packaged functions, there are a lot of awkwardness when trying to develop a project. This project can be used as a reference to help them get started quickly. On the other hand, these good general-purpose functions such as version_compare/addslashes/number_format can also be used directly in the golang project.

**Comment by syyongx** [comment]
> As aked me `why` too :D. However, if you would implement `strtotime` full like in `PHP` with relative time formats, this would be really nice!

I have a plan to implement this function, but there is no specific time.

**Comment by rkl-** [comment]
> > As aked me `why` too :D. However, if you would implement `strtotime` full like in `PHP` with relative time formats, this would be really nice!
> 
> I have a plan to implement this function, but there is no specific time.

Thats nice. However, you can use the original php implementation written in C. The date_parser for example is an PHP extension. You can compile it as shared library and use the function `timelib_strtotime` from Go. A nice wrapper for all the stuff and well done ;).
