### ISSUE TITLE
32位的机器  随机数方法会溢出

### ISSUE THREAD

**Issue by yymmhh** [syyongx/php2go#13]
func Rand(min, max int) int {
	if min > max {
		panic("min: min cannot be greater than max")
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	n := r.Intn(math.MaxInt32)
	return n/((math.MaxInt32+1)/(max-min+1)) + min
	return 1
}

把加一去掉就可以了

**Comment by syyongx** [comment]
f35345662566c24773d0a014c0e8c621c43fa4f6 has fixed it
