### ISSUE TITLE
windows go get fail

### ISSUE THREAD

**Issue by mj520** [syyongx/php2go#17]
$ go get github.com/syyongx/php2go
# github.com/syyongx/php2go
syyongx\php2go\php_unix.go:11:9: undefined: syscall.Umask
syyongx\php2go\php_unix.go:16:8: undefined: syscall.Statfs_t
syyongx\php2go\php_unix.go:17:9: undefined: syscall.Statfs
syyongx\php2go\php_unix.go:26:8: undefined: syscall.Statfs_t
syyongx\php2go\php_unix.go:27:9: undefined: syscall.Statfs

**Comment by fgm** [comment]
This looks like a missing build tag: syscall is protected by build tags to only expose syscalls actually available on the compile target (current systeml by default).

**Comment by mj520** [comment]
When can it be repaired?

**Comment by xj13568542105** [comment]
I also met the same problem as above. How to deal with it

**Comment by syyongx** [comment]
In the new submission, solve this problem, you can try again.
