### ISSUE TITLE
trim is a bug

### ISSUE THREAD

**Issue by welllog** [syyongx/php2go#22]
Trim method is implemented incorrectly

**Comment by fgm** [comment]
Could you be more specific ? As I see it:
- the mask parameter should  be a string, not a variadic of strings
- the current implementation only uses the first string in the slice generated from the variadic arguments

Is this what you are referring to, or something else ?

**Comment by syyongx** [comment]
Thanks for your feedback, the bug has been fixed.

**Comment by syyongx** [comment]
> * the current implementation only uses the first string in the slice generated from the variadic arguments

The slice type is used to make the function support only one parameter.
