### ISSUE TITLE
round function

### ISSUE THREAD

**Issue by zhuCheer** [syyongx/php2go#29]
round function in php have tow params，but in this pkg just only one param；It is can not return a decimal.

**Comment by SwankyTigerYY** [comment]
func main() {
	fmt.Println(Round(8.1413546578, 1))
	//fmt.Println(php.Date("2006-01-02 15:04:05", php.Time())) //时间
}

func Round(value float64, prec int) float64 {
	param := 1
	for i := 0; i < prec; i++ {
		param = param * 10
	}
	return math.Floor(value*float64(param) + 0.5) / float64(param)
}

**Comment by syyongx** [comment]
Fixed it. thanks!
