### ISSUE TITLE
go get fail 

### ISSUE THREAD

**Issue by mingyun** [syyongx/php2go#3]
```js
λ go version
go version go1.7.3 windows/amd64
λ go get github.com/syyongx/php2go
# github.com/syyongx/php2go
D:\golangcode\src\github.com\syyongx\php2go\php.go:977: u.Hostname undefined (type *url.URL has no field or method Hostname)
D:\golangcode\src\github.com\syyongx\php2go\php.go:980: u.Port undefined (type *url.URL has no field or method Port)
D:\golangcode\src\github.com\syyongx\php2go\php.go:1589: undefined: syscall.Statfs_t
D:\golangcode\src\github.com\syyongx\php2go\php.go:1590: undefined: syscall.Statfs
D:\golangcode\src\github.com\syyongx\php2go\php.go:1600: undefined: syscall.Statfs_t
D:\golangcode\src\github.com\syyongx\php2go\php.go:1601: undefined: syscall.Statfs
D:\golangcode\src\github.com\syyongx\php2go\php.go:1615: undefined: syscall.Umask
```

**Comment by syyongx** [comment]
>D:\golangcode\src\github.com\syyongx\php2go\php.go:977: u.Hostname undefined (type *url.URL has no field or method Hostname)
>D:\golangcode\src\github.com\syyongx\php2go\php.go:980: u.Port undefined (type *url.URL has no field or method Port)

Because your version of Go is too old. Please see 19655824dc446ae32bf835bf64c6d0310c935e5b

>D:\golangcode\src\github.com\syyongx\php2go\php.go:1589: undefined: syscall.Statfs_t
>D:\golangcode\src\github.com\syyongx\php2go\php.go:1590: undefined: syscall.Statfs
>D:\golangcode\src\github.com\syyongx\php2go\php.go:1600: undefined: syscall.Statfs_t
>D:\golangcode\src\github.com\syyongx\php2go\php.go:1601: undefined: syscall.Statfs
>D:\golangcode\src\github.com\syyongx\php2go\php.go:1615: undefined: syscall.Umask

DiskFreeSpace & DiskTotalSpace funcs now only  supports Unix/Linux operating systems. I have a comment on the function.

**Comment by syyongx** [comment]
c59892ce02362eb31c3143374da5315b255ff27b Cross-platform incompatible functions have been removed.
