### ISSUE TITLE
数组部分没有排序算法吗

### ISSUE THREAD

**Issue by cuishuang** [syyongx/php2go#5]
数组部分没有排序算法吗^_^

**Comment by syyongx** [comment]
考虑 Go 已经提供了很好用的排序包。另外再去实现要考虑各种类型，这样的封装在实际使用上就没太多实际意义。

**Comment by cuishuang** [comment]
thx

syyong.x <notifications@github.com> 于2019年4月23日周二 下午2:35写道：
